<CUF xmlns="x-schema:CufSchema.xml" xmlns:Ibis="http://www.brinkgroep.nl/ibis/xml" AANMAAKDATUMTIJD="2025-05-07T13:56:33">
  <PROJECTGEGEVENS CUF_VERSIE="4.003" SYSTEEMHUIS="BRINK" AANMAAKDATUM="2025-05-07" PROJECTNUMMER="test kleine begroting" PROJECTNAAM="" CALCULATOR="calculator" OPDRACHTGEVER="opdrachtgever" VALUTA="EUR" EURO_KOERS="1.00000"> </PROJECTGEGEVENS>
  <SORTEERCODES SORTERING="cclcde" FUNCTIE="De code van de calculatie regel"> </SORTEERCODES>
  <SORTEERCODES SORTERING="stk" FUNCTIE="De totalen van deze post worden apart verzameld en bijgehouden"> </SORTEERCODES>
  <SORTEERCODES SORTERING="altcde" FUNCTIE="De alternatieve code"> </SORTEERCODES>
  <SORTEERCODES SORTERING="bwcarb" FUNCTIE="Nacalculatiecode voor arbeid"> </SORTEERCODES>
  <SORTEERCODES SORTERING="bwcmta" FUNCTIE="Nacalculatiecode voor materiaal"> </SORTEERCODES>
  <SORTEERCODES SORTERING="bwcmte" FUNCTIE="Nacalculatiecode voor materieel"> </SORTEERCODES>
  <SORTEERCODES SORTERING="bwcoda" FUNCTIE="Nacalculatiecode voor onderaanneming"> </SORTEERCODES>
  <SORTEERCODES SORTERING="loccde" FUNCTIE="Locatie codering"> </SORTEERCODES>
  <SORTEERCODES SORTERING="plncde" FUNCTIE="Plan codering"> </SORTEERCODES>
  <SORTEERCODES SORTERING="eanartcde" FUNCTIE="GTIN code van het artikel"> </SORTEERCODES>
  <SORTEERCODES SORTERING="bstcde" FUNCTIE="Bestekcodering"> </SORTEERCODES>
  <SORTEERCODES SORTERING="pstaard" FUNCTIE="Aard van de (sub)bestekspost t.b.v. afrekening"> </SORTEERCODES>
  <SORTEERCODES SORTERING="prdfact" FUNCTIE="Productie capaciteit"> </SORTEERCODES>
  <SORTEERCODES SORTERING="vstind" FUNCTIE="Bij * is de eenheidsprijs handmatig ingevuld"> </SORTEERCODES>
  <SORTEERCODES SORTERING="enhprs" FUNCTIE="De handmatig ingevulde eenheidsprijs"> </SORTEERCODES>
  <SORTEERCODES SORTERING="levgtincde" FUNCTIE="Leverancier GLN code"> </SORTEERCODES>
  <SORTEERCODES SORTERING="levnaam" FUNCTIE="Leverancier naam"> </SORTEERCODES>
  <SORTEERCODES SORTERING="levartcode" FUNCTIE="Leverancier artikel code"> </SORTEERCODES>
  <SORTEERCODES SORTERING="ibcode" FUNCTIE="unieke code voor Ib.nl"> </SORTEERCODES>
  <SORTEERCODES SORTERING="beschsts" FUNCTIE="Beschikbaarheidsstatus voor Ib.nl"> </SORTEERCODES>
  <SORTEERCODES SORTERING="bloksts" FUNCTIE="Blokkeerstatus voor Ib.nl"> </SORTEERCODES>
  <SORTEERCODES SORTERING="ondcde" FUNCTIE="Onderhoudscode"> </SORTEERCODES>
  <SORTEERCODES SORTERING="offertenaam" FUNCTIE="Offertenaam"> </SORTEERCODES>

  <BEGROTING UREN="0.00000" LOONKOSTEN="0.00000" MATERIAALKOSTEN="894.62880" MATERIEELKOSTEN="0.00000" ONDERAANNEMING="0.00000" OVERIGE_KOSTEN="0.00000" Ibis:NETTO_MATERIAALKOSTEN="758.16000">
    <BUNDELING CODE="24" OMSCHRIJVING="RUWBOUW TIMMERWERK" EENHEID="" TERUGDEEL_HOEVEELHEID="0.00000" UREN="0.00000" LOONKOSTEN="0.00000" MATERIAALKOSTEN="894.62880" MATERIEELKOSTEN="0.00000" ONDERAANNEMING="0.00000" Ibis:AANDUIDING="1" Ibis:NETTO_MATERIAALKOSTEN="758.16000">
      <SORTEERCODE SORTERING="bstcde" WAARDE="24"> </SORTEERCODE>
      <BUNDELING CODE="" OMSCHRIJVING="NIEUWE VLOERCONSTRUCTIE 2e VERDIEPING" EENHEID="" TERUGDEEL_HOEVEELHEID="0.00000" UREN="0.00000" LOONKOSTEN="0.00000" MATERIAALKOSTEN="894.62880" MATERIEELKOSTEN="0.00000" ONDERAANNEMING="0.00000" Ibis:AANDUIDING="2" Ibis:NETTO_MATERIAALKOSTEN="758.16000">
        <SORTEERCODE SORTERING="bstcde" WAARDE="24.01a"> </SORTEERCODE>

        <BEGROTINGSREGEL OMSCHRIJVING="nieuw te vervaardigen houten balklaag tpv oorspr.verdieping" HOEVEELHEID="0.00000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" BTW="0">
          <SORTEERCODE SORTERING="stk" WAARDE="."> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="gehele post als verrekenbare stelpost opgenomen. feitelijke werkwijze afhankelijk van hoedanigheid dakconstructie, sterkte afschot en bepalingen constructeur" HOEVEELHEID="0.00000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" BTW="0">
          <SORTEERCODE SORTERING="stk" WAARDE="."> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="aanbrengen over bestaand plafond" HOEVEELHEID="0.00000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" BTW="0">
          <SORTEERCODE SORTERING="stk" WAARDE="."> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="aanname h.o.h. afstand 0,4m (ntb door constructeur)" HOEVEELHEID="0.00000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" BTW="0">
          <SORTEERCODE SORTERING="stk" WAARDE="-"> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="balklaag te bevestigen aan randbalken/ dakopstand" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" UUR_NORM="0.00000" UUR_TARIEF="0.00000" BTW="">
          <SORTEERCODE SORTERING="stk" WAARDE=""> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="Vuren Geschaafd 70*170 mm" HOEVEELHEID_EENHEID="m1" HOEVEELHEID="250.00000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" MATERIAALPRIJS="6.37200" BTW="21" Ibis:NETTO_MATERIAALPRIJS="5.40000">
          <SORTEERCODE SORTERING="stk" WAARDE="M"> </SORTEERCODE>
          <SORTEERCODE SORTERING="bwcmta" WAARDE="H 10.02.01.21"> </SORTEERCODE>
          <SORTEERCODE SORTERING="bstcde" WAARDE="S"> </SORTEERCODE>
          <SORTEERCODE SORTERING="loccde" WAARDE="r"> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="Handelsmaat" HOEVEELHEID_EENHEID="m1" HOEVEELHEID="3.90000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" BTW="0">
          <SORTEERCODE SORTERING="stk" WAARDE="-"> </SORTEERCODE>
          <SORTEERCODE SORTERING="loccde" WAARDE="r"> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="aantal lengtes balken" HOEVEELHEID_EENHEID="st" HOEVEELHEID="36.00000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" BTW="0">
          <SORTEERCODE SORTERING="stk" WAARDE="-"> </SORTEERCODE>
          <SORTEERCODE SORTERING="loccde" WAARDE="r"> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="hoh-afstand" HOEVEELHEID_EENHEID="m1" HOEVEELHEID="0.30000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" BTW="0">
          <SORTEERCODE SORTERING="stk" WAARDE="-"> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="aantal extra startbalken opgenomen" HOEVEELHEID_EENHEID="st" HOEVEELHEID="4.00000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" BTW="0">
          <SORTEERCODE SORTERING="stk" WAARDE="-"> </SORTEERCODE>
        </BEGROTINGSREGEL>

        <BEGROTINGSREGEL OMSCHRIJVING="aantal zijden randbalken opgenomen" HOEVEELHEID_EENHEID="st" HOEVEELHEID="0.00000" INZET="1.00000" HOEVEELHEID_FACTOR="1.00000" BTW="0">
          <SORTEERCODE SORTERING="stk" WAARDE="-"> </SORTEERCODE>
        </BEGROTINGSREGEL>

      </BUNDELING>
    </BUNDELING>
  </BEGROTING>

  <STAARTGEGEVENS AANNEEMSOM="894.62880"> </STAARTGEGEVENS>
</CUF>
